_commit: v1.12.1-4-g3565bdb
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Notification Sender
homepageEnabled: true
homepageGroup: Web
homepageIcon: ntfy
homepageName: ntfy.sh
ingHost: ping.crt.lol
ingName: ntfy
ingress: false
labels: 'app: ntfy'
name: ntfy.sh
namespace: ntfy
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://ntfy.sh
url: https://github.com/charlesthomas/homelab-ntfy.sh
