---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  server.yml: |
    attachment-cache-dir: /var/cache/ntfy/attachments
    auth-default-access: deny-all
    auth-file: /var/cache/ntfy/user.db
    base-url: https://ping.crt.lol
    behind-proxy: true
    cache-file: /var/cache/ntfy/cache.db
