---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: ntfy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
  volumeMode: Filesystem
